(()=>{
const nav=document.querySelector('.admin-tabs'),main=document.querySelector('.admin-main');
if(!nav||!main||document.querySelector('[data-tab="instagramCover"]'))return;
const editionId=window.DEUCAPA_EDITION?.id||'edicao-01',STORE=`deuCapaInstagramCoverV2::${editionId}`;
const sizes={portrait:[1080,1350],square:[1080,1080],story:[1080,1920]};
const uid=()=>`el-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
const baseElements=()=>[
 {id:uid(),type:'text',role:'label',text:'REVISTA DIGITAL',x:82,y:115,w:520,size:30,color:'#c7a56a',font:'Arial',weight:'700',align:'left',rotation:0},
 {id:uid(),type:'text',role:'title',text:'DEU CAPA',x:82,y:310,w:850,size:150,color:'#ffffff',font:'Georgia',weight:'400',align:'left',rotation:0},
 {id:uid(),type:'rect',x:82,y:570,w:210,h:4,color:'#c7a56a',rotation:0},
 {id:uid(),type:'text',role:'body',text:'HISTÓRIAS QUE MERECEM SER VISTAS',x:82,y:640,w:760,size:38,color:'#ffffff',font:'Arial',weight:'500',align:'left',rotation:0},
 {id:uid(),type:'text',role:'footer',text:'@DEUCAPA',x:82,y:1210,w:500,size:27,color:'#c7a56a',font:'Arial',weight:'700',align:'left',rotation:0}
];
const defaults={format:'portrait',background:'#0b0b0b',backgroundImage:'',overlay:'#050505',overlayAlpha:52,elements:baseElements()};
let state={...defaults,elements:baseElements()},selected=null,drag=null,images=new Map(),history=[],future=[];
try{const old=JSON.parse(localStorage.getItem(STORE)||'null');if(old&&Array.isArray(old.elements))state={...defaults,...old,elements:old.elements}}catch{}
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
function snap(){history.push(JSON.stringify(state));if(history.length>40)history.shift();future=[]}
function restore(raw){if(!raw)return;state=JSON.parse(raw);selected=null;loadAllImages().then(()=>{renderLayers();renderProps();draw();save()})}
function undo(){if(!history.length)return;future.push(JSON.stringify(state));restore(history.pop())}
function redo(){if(!future.length)return;history.push(JSON.stringify(state));restore(future.pop())}
const btn=document.createElement('button');btn.dataset.tab='instagramCover';btn.textContent='Criador Instagram';nav.appendChild(btn);
const panel=document.createElement('section');panel.className='tab-panel';panel.dataset.panel='instagramCover';
panel.innerHTML=`<div class="panel-card igc-shell">
<div class="igc-topbar"><div><h2>Estúdio Instagram</h2><p class="top-note">Editor visual estilo Canva: clique, arraste, redimensione e organize os elementos.</p></div><div class="igc-top-actions"><select id="igcFormat"><option value="portrait">Feed 1080×1350</option><option value="square">Quadrado 1080×1080</option><option value="story">Story 1080×1920</option></select><button id="igcUndo" type="button">↶</button><button id="igcRedo" type="button">↷</button><button id="igcDownload" class="primary-btn" type="button">Baixar PNG</button></div></div>
<div class="igc-studio">
<aside class="igc-tools">
<h3>Adicionar</h3>
<button type="button" data-add="title"><b>T</b><span>Título</span></button>
<button type="button" data-add="text"><b>T</b><span>Texto</span></button>
<button type="button" data-add="label"><b>Aa</b><span>Etiqueta</span></button>
<button type="button" data-add="rect"><b>□</b><span>Forma</span></button>
<label class="igc-tool-upload"><b>▧</b><span>Imagem</span><input id="igcAddImage" type="file" accept="image/*"></label>
<button type="button" id="igcUseEditionCover"><b>◫</b><span>Capa da edição</span></button>
<hr><h3>Design</h3>
<button type="button" data-template="premium"><b>✦</b><span>Premium</span></button>
<button type="button" data-template="editorial"><b>▤</b><span>Editorial</span></button>
<button type="button" data-template="minimal"><b>○</b><span>Minimal</span></button>
</aside>
<section class="igc-workspace"><div class="igc-canvas-stage"><canvas id="igcCanvas" width="1080" height="1350"></canvas></div><div class="igc-hint">Arraste para mover · alça no canto para redimensionar · Delete para excluir · setas para ajuste fino</div></section>
<aside class="igc-sidebar">
<div class="igc-bg-panel"><h3>Fundo</h3><div class="igc-mini-grid"><label>Cor<input id="igcBg" type="color"></label><label>Overlay<input id="igcOverlay" type="color"></label></div><label>Escurecer<input id="igcOverlayAlpha" type="range" min="0" max="90"></label><label class="igc-bg-upload">Trocar foto<input id="igcBgImage" type="file" accept="image/*"></label><button id="igcClearBg" type="button" class="text-btn">Remover foto de fundo</button></div>
<div id="igcProps" class="igc-props"><h3>Propriedades</h3><p class="igc-empty-props">Selecione um elemento na arte.</p></div>
<div class="igc-layers"><div class="igc-layer-head"><h3>Camadas</h3><div><button id="igcLayerUp" type="button" title="Subir camada">↑</button><button id="igcLayerDown" type="button" title="Descer camada">↓</button></div></div><div id="igcLayerList"></div></div>
</aside>
</div></div>`;
main.appendChild(panel);
const $=id=>document.getElementById(id),canvas=$('igcCanvas'),ctx=canvas.getContext('2d');
function rgba(hex,a){const h=String(hex||'#000').replace('#',''),n=parseInt(h.length===3?h.split('').map(c=>c+c).join(''):h,16)||0;return`rgba(${n>>16&255},${n>>8&255},${n&255},${a})`}
function loadImg(src){return new Promise(resolve=>{if(!src)return resolve(null);const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>resolve(null);im.src=src})}
async function loadAllImages(){images.clear();if(state.backgroundImage){const im=await loadImg(state.backgroundImage);if(im)images.set('background',im)}for(const e of state.elements){if(e.type==='image'&&e.src){const im=await loadImg(e.src);if(im)images.set(e.id,im)}}}
function cover(im,x,y,w,h){const s=Math.max(w/im.width,h/im.height),dw=im.width*s,dh=im.height*s;ctx.drawImage(im,x+(w-dw)/2,y+(h-dh)/2,dw,dh)}
function fontString(e){return`${e.weight||'400'} ${Math.max(8,e.size||30)}px ${e.font||'Arial'}`}
function wrapLines(e){ctx.font=fontString(e);const words=String(e.text||'').split(/\s+/),lines=[];let line='';for(const word of words){const t=line?line+' '+word:word;if(ctx.measureText(t).width>(e.w||500)&&line){lines.push(line);line=word}else line=t}if(line)lines.push(line);return lines}
function bbox(e){if(e.type==='text'){const lines=wrapLines(e),lh=(e.size||30)*1.18;return{x:e.x,y:e.y,w:e.w||500,h:Math.max(lh,lines.length*lh)}}return{x:e.x,y:e.y,w:e.w||100,h:e.h||100}}
function drawElement(e,forExport=false){ctx.save();const b=bbox(e),cx=b.x+b.w/2,cy=b.y+b.h/2;ctx.translate(cx,cy);ctx.rotate((e.rotation||0)*Math.PI/180);ctx.translate(-cx,-cy);if(e.type==='rect'){ctx.fillStyle=e.color||'#fff';ctx.fillRect(e.x,e.y,e.w,e.h)}else if(e.type==='image'){const im=images.get(e.id);if(im){ctx.save();ctx.beginPath();ctx.rect(e.x,e.y,e.w,e.h);ctx.clip();cover(im,e.x,e.y,e.w,e.h);ctx.restore()}}else if(e.type==='text'){ctx.font=fontString(e);ctx.fillStyle=e.color||'#fff';ctx.textBaseline='top';ctx.textAlign=e.align||'left';const x=e.align==='center'?e.x+e.w/2:e.align==='right'?e.x+e.w:e.x,lh=(e.size||30)*1.18;wrapLines(e).forEach((line,i)=>ctx.fillText(line,x,e.y+i*lh))}ctx.restore();if(!forExport&&selected===e.id)drawSelection(e)}
function drawSelection(e){const b=bbox(e);ctx.save();ctx.strokeStyle='#5b8def';ctx.lineWidth=Math.max(2,canvas.width/500);ctx.setLineDash([10,7]);ctx.strokeRect(b.x-6,b.y-6,b.w+12,b.h+12);ctx.setLineDash([]);ctx.fillStyle='#fff';ctx.strokeStyle='#5b8def';ctx.lineWidth=3;const r=12;ctx.beginPath();ctx.arc(b.x+b.w+6,b.y+b.h+6,r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore()}
function draw(forExport=false){const [w,h]=sizes[state.format]||sizes.portrait;canvas.width=w;canvas.height=h;ctx.clearRect(0,0,w,h);ctx.fillStyle=state.background||'#0b0b0b';ctx.fillRect(0,0,w,h);const bg=images.get('background');if(bg)cover(bg,0,0,w,h);ctx.fillStyle=rgba(state.overlay,Number(state.overlayAlpha||0)/100);ctx.fillRect(0,0,w,h);state.elements.forEach(e=>drawElement(e,forExport));if(!forExport&&$('igcFormat'))$('igcFormat').value=state.format}
function point(ev){const r=canvas.getBoundingClientRect();return{x:(ev.clientX-r.left)*canvas.width/r.width,y:(ev.clientY-r.top)*canvas.height/r.height}}
function hit(p){for(let i=state.elements.length-1;i>=0;i--){const e=state.elements[i],b=bbox(e);if(p.x>=b.x-8&&p.x<=b.x+b.w+8&&p.y>=b.y-8&&p.y<=b.y+b.h+8)return e}return null}
function isResize(p,e){const b=bbox(e);return Math.hypot(p.x-(b.x+b.w+6),p.y-(b.y+b.h+6))<30}
canvas.addEventListener('pointerdown',ev=>{const p=point(ev),e=hit(p);if(!e){selected=null;renderProps();renderLayers();draw();return}selected=e.id;snap();const b=bbox(e),mode=isResize(p,e)?'resize':'move';drag={id:e.id,mode,start:p,orig:{x:e.x,y:e.y,w:b.w,h:b.h}};canvas.setPointerCapture(ev.pointerId);renderProps();renderLayers();draw()});
canvas.addEventListener('pointermove',ev=>{if(!drag)return;const p=point(ev),e=state.elements.find(x=>x.id===drag.id);if(!e)return;const dx=p.x-drag.start.x,dy=p.y-drag.start.y;if(drag.mode==='move'){e.x=Math.round(drag.orig.x+dx);e.y=Math.round(drag.orig.y+dy)}else{e.w=Math.max(40,Math.round(drag.orig.w+dx));if(e.type!=='text')e.h=Math.max(30,Math.round(drag.orig.h+dy));else e.size=Math.max(12,Math.round((e.size||30)*(e.w/drag.orig.w)))}draw();syncProps()});
canvas.addEventListener('pointerup',()=>{if(drag){drag=null;save();renderLayers()}});
function addElement(kind){snap();const [w,h]=sizes[state.format],cx=Math.round(w*.18),cy=Math.round(h*.22);let e;if(kind==='title')e={id:uid(),type:'text',text:'NOVO TÍTULO',x:cx,y:cy,w:Math.round(w*.65),size:120,color:'#ffffff',font:'Georgia',weight:'400',align:'left',rotation:0};else if(kind==='text')e={id:uid(),type:'text',text:'Digite seu texto aqui',x:cx,y:cy,w:Math.round(w*.6),size:42,color:'#ffffff',font:'Arial',weight:'400',align:'left',rotation:0};else if(kind==='label')e={id:uid(),type:'text',text:'DEU CAPA',x:cx,y:cy,w:420,size:28,color:'#c7a56a',font:'Arial',weight:'700',align:'left',rotation:0};else e={id:uid(),type:'rect',x:cx,y:cy,w:260,h:80,color:'#c7a56a',rotation:0};state.elements.push(e);selected=e.id;save();renderProps();renderLayers();draw()}
function addImage(src){snap();const [w,h]=sizes[state.format],e={id:uid(),type:'image',src,x:Math.round(w*.2),y:Math.round(h*.2),w:Math.round(w*.55),h:Math.round(h*.45),rotation:0};state.elements.push(e);selected=e.id;loadImg(src).then(im=>{if(im)images.set(e.id,im);save();renderProps();renderLayers();draw()})}
function renderProps(){const box=$('igcProps'),e=state.elements.find(x=>x.id===selected);if(!e){box.innerHTML='<h3>Propriedades</h3><p class="igc-empty-props">Selecione um elemento na arte.</p>';return}let html=`<div class="igc-prop-title"><h3>Propriedades</h3><button id="igcDelete" type="button">Excluir</button></div>`;if(e.type==='text')html+=`<label>Texto<textarea id="propText" rows="3"></textarea></label><div class="igc-mini-grid"><label>Fonte<select id="propFont"><option>Georgia</option><option>Arial</option><option>Times New Roman</option><option>Verdana</option><option>Trebuchet MS</option></select></label><label>Peso<select id="propWeight"><option value="400">Normal</option><option value="500">Médio</option><option value="700">Negrito</option></select></label></div><div class="igc-mini-grid"><label>Tamanho<input id="propSize" type="number" min="10" max="260"></label><label>Cor<input id="propColor" type="color"></label></div><label>Alinhamento<select id="propAlign"><option value="left">Esquerda</option><option value="center">Centro</option><option value="right">Direita</option></select></label>`;else if(e.type==='rect')html+=`<label>Cor<input id="propColor" type="color"></label>`;html+=`<div class="igc-mini-grid"><label>X<input id="propX" type="number"></label><label>Y<input id="propY" type="number"></label></div><div class="igc-mini-grid"><label>Largura<input id="propW" type="number" min="20"></label>${e.type==='text'?'':`<label>Altura<input id="propH" type="number" min="20"></label>`}</div><label>Rotação<input id="propRot" type="range" min="-180" max="180"><output id="propRotOut"></output></label><div class="igc-prop-actions"><button id="igcDuplicate" type="button">Duplicar</button><button id="igcFront" type="button">Frente</button><button id="igcBack" type="button">Fundo</button></div>`;box.innerHTML=html;bindProps(e)}
function bindProps(e){const bind=(id,key,parser=v=>v)=>{const el=$(id);if(!el)return;el.value=e[key]??'';el.addEventListener('input',()=>{if(!el.dataset.started){snap();el.dataset.started='1'}e[key]=parser(el.value);save();draw();renderLayers()});el.addEventListener('change',()=>delete el.dataset.started)};bind('propText','text');bind('propFont','font');bind('propWeight','weight');bind('propSize','size',Number);bind('propColor','color');bind('propAlign','align');bind('propX','x',Number);bind('propY','y',Number);bind('propW','w',Number);bind('propH','h',Number);bind('propRot','rotation',Number);if($('propRotOut')){$('propRotOut').textContent=`${e.rotation||0}°`;$('propRot').addEventListener('input',()=>$('propRotOut').textContent=`${e.rotation||0}°`)}$('igcDelete').onclick=deleteSelected;$('igcDuplicate').onclick=duplicateSelected;$('igcFront').onclick=()=>moveLayer('front');$('igcBack').onclick=()=>moveLayer('back')}
function syncProps(){const e=state.elements.find(x=>x.id===selected);if(!e)return;[['propX','x'],['propY','y'],['propW','w'],['propH','h'],['propSize','size']].forEach(([id,k])=>{if($(id))$(id).value=Math.round(e[k]||0)})}
function renderLayers(){const box=$('igcLayerList');box.innerHTML='';[...state.elements].reverse().forEach(e=>{const row=document.createElement('button');row.type='button';row.className='igc-layer'+(e.id===selected?' active':'');row.innerHTML=`<span>${e.type==='text'?'T':e.type==='image'?'▧':'□'}</span><b>${e.type==='text'?(e.text||'Texto').slice(0,24):e.type==='image'?'Imagem':'Forma'}</b>`;row.onclick=()=>{selected=e.id;renderProps();renderLayers();draw()};box.appendChild(row)})}
function deleteSelected(){if(!selected)return;snap();state.elements=state.elements.filter(e=>e.id!==selected);images.delete(selected);selected=null;save();renderProps();renderLayers();draw()}
function duplicateSelected(){const e=state.elements.find(x=>x.id===selected);if(!e)return;snap();const c={...e,id:uid(),x:e.x+35,y:e.y+35};state.elements.push(c);if(e.type==='image'&&images.get(e.id))images.set(c.id,images.get(e.id));selected=c.id;save();renderProps();renderLayers();draw()}
function moveLayer(where){const i=state.elements.findIndex(e=>e.id===selected);if(i<0)return;snap();const [e]=state.elements.splice(i,1);if(where==='front')state.elements.push(e);else if(where==='back')state.elements.unshift(e);else if(where==='up')state.elements.splice(Math.min(state.elements.length,i+1),0,e);else state.elements.splice(Math.max(0,i-1),0,e);save();renderLayers();draw()}
function readFile(input,cb){const f=input.files?.[0];if(!f)return;if(!f.type.startsWith('image/'))return alert('Escolha uma imagem válida.');if(f.size>7*1024*1024)return alert('Use imagem de até 7 MB.');const r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(f)}
function applyTemplate(name){snap();const [w,h]=sizes[state.format];if(name==='premium'){state.background='#0a0a0a';state.overlay='#050505';state.overlayAlpha=55;state.elements=baseElements()}else if(name==='editorial'){state.background='#1a0d08';state.overlay='#120804';state.overlayAlpha=38;state.elements=[{id:uid(),type:'text',text:'DEU CAPA',x:w*.1,y:h*.13,w:w*.8,size:145,color:'#f4efe6',font:'Georgia',weight:'400',align:'center',rotation:0},{id:uid(),type:'text',text:'EDIÇÃO ESPECIAL',x:w*.2,y:h*.62,w:w*.6,size:34,color:'#c7a56a',font:'Arial',weight:'700',align:'center',rotation:0},{id:uid(),type:'rect',x:w*.35,y:h*.72,w:w*.3,h:3,color:'#c7a56a',rotation:0}]}else{state.background='#f4efe6';state.overlay='#ffffff';state.overlayAlpha=0;state.elements=[{id:uid(),type:'text',text:'DEU CAPA',x:w*.08,y:h*.18,w:w*.84,size:130,color:'#111111',font:'Georgia',weight:'400',align:'left',rotation:0},{id:uid(),type:'text',text:'REVISTA DIGITAL',x:w*.08,y:h*.43,w:w*.6,size:28,color:'#9b7948',font:'Arial',weight:'700',align:'left',rotation:0},{id:uid(),type:'rect',x:w*.08,y:h*.52,w:180,h:4,color:'#111111',rotation:0}]};selected=null;save();loadAllImages().then(()=>{renderProps();renderLayers();draw()})}
panel.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addElement(b.dataset.add));panel.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>applyTemplate(b.dataset.template));
$('igcAddImage').onchange=()=>readFile($('igcAddImage'),addImage);$('igcBgImage').onchange=()=>readFile($('igcBgImage'),src=>{snap();state.backgroundImage=src;loadImg(src).then(im=>{if(im)images.set('background',im);save();draw()})});
$('igcUseEditionCover').onclick=()=>{try{const c=JSON.parse(localStorage.getItem('deuCapaConfig')||'{}');if(!c.heroImage)return alert('A edição ainda não tem uma capa definida.');snap();state.backgroundImage=c.heroImage;loadImg(c.heroImage).then(im=>{if(im)images.set('background',im);save();draw()})}catch{}};
$('igcClearBg').onclick=()=>{snap();state.backgroundImage='';images.delete('background');save();draw()};
$('igcBg').value=state.background;$('igcOverlay').value=state.overlay;$('igcOverlayAlpha').value=state.overlayAlpha;$('igcFormat').value=state.format;
$('igcBg').oninput=e=>{state.background=e.target.value;save();draw()};$('igcOverlay').oninput=e=>{state.overlay=e.target.value;save();draw()};$('igcOverlayAlpha').oninput=e=>{state.overlayAlpha=Number(e.target.value);save();draw()};
$('igcFormat').onchange=e=>{snap();const old=sizes[state.format],next=sizes[e.target.value],sx=next[0]/old[0],sy=next[1]/old[1];state.elements.forEach(el=>{el.x=Math.round(el.x*sx);el.y=Math.round(el.y*sy);el.w=Math.round((el.w||100)*sx);if(el.h)el.h=Math.round(el.h*sy)});state.format=e.target.value;save();draw();renderProps()};
$('igcUndo').onclick=undo;$('igcRedo').onclick=redo;$('igcLayerUp').onclick=()=>moveLayer('up');$('igcLayerDown').onclick=()=>moveLayer('down');
$('igcDownload').onclick=()=>{const prev=selected;selected=null;draw(true);const a=document.createElement('a');a.download=`deu-capa-${state.format}-${Date.now()}.png`;a.href=canvas.toDataURL('image/png',1);a.click();selected=prev;draw()};
window.addEventListener('keydown',e=>{if(!panel.classList.contains('active'))return;const tag=document.activeElement?.tagName;if(['INPUT','TEXTAREA','SELECT'].includes(tag))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'){e.preventDefault();duplicateSelected();return}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();deleteSelected();return}const el=state.elements.find(x=>x.id===selected);if(el&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();snap();const step=e.shiftKey?10:1;if(e.key==='ArrowLeft')el.x-=step;if(e.key==='ArrowRight')el.x+=step;if(e.key==='ArrowUp')el.y-=step;if(e.key==='ArrowDown')el.y+=step;save();syncProps();draw()}});
btn.onclick=()=>{document.querySelectorAll('.admin-tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.remove('active'));btn.classList.add('active');panel.classList.add('active');draw()};
loadAllImages().then(()=>{renderLayers();renderProps();draw()});
})();