const DEFAULT_CONFIG={editionLabel:'EDIÇÃO #01 · 2026',heroTitle1:'DEU',heroTitle2:'CAPA',heroText:'Muito mais que uma revista. É sobre histórias que merecem ser vistas.',heroImage:'assets/hero.jpg',essayTitle:'Luz que conta histórias',essayText:'Cada clique revela mais que imagens. Revela essência, verdade e emoção.',essayImage:'assets/essay.jpg',galleryImages:['assets/p1.jpg','assets/p2.jpg','assets/hero.jpg','assets/p3.jpg','assets/essay.jpg'],sponsorTitle:'Coloque sua marca em evidência.',sponsorText:'Associe sua empresa à DEU CAPA e alcance um público conectado a histórias, imagem, eventos e experiências.'};
const DEFAULT_PARTICIPANTS=[{name:'Júlia Martins',role:'São Paulo — SP',bio:'Presença, personalidade e uma história que merece ser vista.',photo:'assets/p1.jpg'},{name:'Pedro Henrique',role:'Curitiba — PR',bio:'Um olhar autoral para quem transforma presença em narrativa visual.',photo:'assets/p2.jpg'},{name:'Larissa Almeida',role:'Belo Horizonte — MG',bio:'Elegância, atitude e um ensaio pensado para ficar na memória.',photo:'assets/p3.jpg'},{name:'Gabriel Santos',role:'Salvador — BA',bio:'Histórias reais, fotografadas com estética editorial e identidade.',photo:'assets/p4.jpg'}];
function load(key,fallback){try{const v=JSON.parse(localStorage.getItem(key)||'null');return v||fallback}catch{return fallback}}
const config={...DEFAULT_CONFIG,...load('deuCapaConfig',{})};
const participants=load('deuCapaParticipants',DEFAULT_PARTICIPANTS);
const book=document.getElementById('book'),stage=document.getElementById('stage'),indicator=document.getElementById('pageIndicator'),prevBtn=document.getElementById('prevBtn'),nextBtn=document.getElementById('nextBtn'),firstBtn=document.getElementById('firstBtn'),hint=document.getElementById('hint'),fullscreenBtn=document.getElementById('fullscreenBtn');
const pages=[];let current=0,drag=null,animating=false;
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function img(v,f=''){return String(v||f).replace(/'/g,'%27')}
function addPage(front,cls=''){const p=document.createElement('article');p.className=`page ${cls}`;p.innerHTML=`<div class="page-face">${front}</div><div class="page-back"></div><div class="curl-light"></div><div class="curl-shadow"></div><div class="page-edge"></div>`;book.appendChild(p);pages.push(p);return p}
const cover=addPage(`<div class="cover-shade"></div><div class="cover-content"><div class="edition">${esc(config.editionLabel)}</div><h1>${esc(config.heroTitle1)}<em>${esc(config.heroTitle2)}</em></h1><p>${esc(config.heroText)}</p></div>`,'cover');cover.querySelector('.page-face').style.backgroundImage=`url('${img(config.heroImage,'assets/hero.jpg')}')`;
participants.slice(0,4).forEach((p,i)=>addPage(`<div class="page-inner"><div class="page-photo" style="background-image:url('${img(p.photo,DEFAULT_PARTICIPANTS[i%4].photo)}')"></div><div class="page-copy"><small>PARTICIPANTE ${String(i+1).padStart(2,'0')}</small><h2>${esc(p.name||'Participante')}</h2><p>${esc(p.bio||p.role||'')}</p></div></div>`));
addPage(`<div class="page-inner"><div class="page-photo" style="background-image:url('${img(config.essayImage,'assets/essay.jpg')}');filter:grayscale(1)"></div><div class="page-copy"><small>ENSAIO EM DESTAQUE</small><h2>${esc(config.essayTitle)}</h2><p>${esc(config.essayText)}</p></div></div>`,'dark');
const gallery=config.galleryImages||DEFAULT_CONFIG.galleryImages;
addPage(`<div class="page-inner"><div class="page-photo" style="background-image:url('${img(gallery[2],'assets/hero.jpg')}')"></div><div class="page-copy"><small>GALERIA</small><h2>Momentos <em>que ficam</em></h2><p>Uma seleção visual da edição, agora com a sensação de folhear uma página real.</p></div></div>`);
addPage(`<div class="page-inner"><div class="page-photo" style="background-image:url('${img(gallery[4],'assets/essay.jpg')}')"></div><div class="page-copy"><small>PARA EMPRESAS</small><h2>${esc(config.sponsorTitle)}</h2><p>${esc(config.sponsorText)}</p></div></div>`,'dark');
addPage(`<div class="page-inner"><div class="page-copy" style="text-align:center;align-items:center"><small>FIM DA EDIÇÃO</small><h2 style="font-size:clamp(3rem,10vw,5rem)">DEU CAPA</h2><p>Obrigado por folhear. Volte ao site para conhecer todos os conteúdos e parceiros.</p><a href="index.html?v=8" style="margin-top:26px;color:#9b7948;text-decoration:none;font-weight:600">VOLTAR AO SITE →</a></div></div>`);
function setAngle(page,angle){page.style.transform=`rotateY(${angle}deg)`;const t=Math.min(1,Math.abs(angle)/180);page.querySelector('.curl-shadow').style.opacity=String(Math.sin(t*Math.PI)*.85);page.querySelector('.curl-light').style.opacity=String(Math.sin(t*Math.PI)*.65);page.style.filter=`brightness(${1-.22*Math.sin(t*Math.PI)})`}
function baseRender(){pages.forEach((p,i)=>{p.style.zIndex=String(i<current?i+1:pages.length-i+current);p.classList.toggle('flipped',i<current);p.classList.remove('turning');p.style.transition='none';setAngle(p,i<current?-180:0)});indicator.textContent=`${String(current+1).padStart(2,'0')} / ${String(pages.length).padStart(2,'0')}`;prevBtn.disabled=current===0;nextBtn.disabled=current===pages.length-1;if(current>0)hint.style.display='none'}
function animatePage(page,from,to,duration=520,done){animating=true;page.classList.add('turning');page.style.transition='none';const start=performance.now();function frame(now){const t=Math.min(1,(now-start)/duration),e=1-Math.pow(1-t,3);setAngle(page,from+(to-from)*e);if(t<1)requestAnimationFrame(frame);else{page.classList.remove('turning');animating=false;done?.()}}requestAnimationFrame(frame)}
function next(){if(animating||current>=pages.length-1)return;const p=pages[current];p.style.zIndex=String(pages.length+5);animatePage(p,0,-180,560,()=>{current++;baseRender()})}
function prev(){if(animating||current<=0)return;const p=pages[current-1];p.style.zIndex=String(pages.length+5);animatePage(p,-180,0,560,()=>{current--;baseRender()})}
prevBtn.onclick=prev;nextBtn.onclick=next;firstBtn.onclick=()=>{if(animating)return;current=0;baseRender()};
stage.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();next()}if(e.key==='ArrowLeft'){e.preventDefault();prev()}});
stage.addEventListener('pointerdown',e=>{if(animating)return;const rect=stage.getBoundingClientRect();drag={id:e.pointerId,x:e.clientX,y:e.clientY,dir:null,page:null,angle:0,width:Math.min(rect.width,560)};stage.setPointerCapture?.(e.pointerId)});
stage.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(!drag.dir){if(Math.abs(dx)<8)return;if(Math.abs(dy)>Math.abs(dx)*1.25)return;drag.dir=dx<0?'next':'prev';if(drag.dir==='next'&&current<pages.length-1){drag.page=pages[current];drag.page.style.zIndex=String(pages.length+5)}else if(drag.dir==='prev'&&current>0){drag.page=pages[current-1];drag.page.style.zIndex=String(pages.length+5)}else{drag=null;return}drag.page.classList.add('turning')}
 if(!drag?.page)return;const progress=Math.min(1,Math.abs(dx)/(drag.width*.72));drag.angle=drag.dir==='next'?-180*progress:-180+180*progress;setAngle(drag.page,drag.angle)});
function finishDrag(e){if(!drag||e.pointerId!==drag.id)return;const d=drag;drag=null;if(!d.page)return;const complete=d.dir==='next'?d.angle<-65:d.angle>-115;if(complete){const to=d.dir==='next'?-180:0;animatePage(d.page,d.angle,to,360,()=>{current+=d.dir==='next'?1:-1;baseRender()})}else{const to=d.dir==='next'?0:-180;animatePage(d.page,d.angle,to,300,baseRender)}}
stage.addEventListener('pointerup',finishDrag);stage.addEventListener('pointercancel',finishDrag);
function updateFullscreenLabel(){if(!fullscreenBtn)return;fullscreenBtn.textContent=document.fullscreenElement?'SAIR DA TELA CHEIA':'TELA CHEIA'}
if(fullscreenBtn){if(!document.documentElement.requestFullscreen){fullscreenBtn.style.display='none'}else{fullscreenBtn.addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{} });document.addEventListener('fullscreenchange',updateFullscreenLabel);updateFullscreenLabel()}}
baseRender();